### DISCUSSION TITLE
Default config settings for Bayesian optimization

### DISCUSSION THREAD

**Discussion by TobyBoyne** [TobyBoyne/bark#34] [General]
Here are the default settings for BO with BARK
```yaml
num_init: 5 # (should this be 2*D instead?)
num_iter: 100
model: BARK

model_params:
  num_chains: 4
  num_samples: 10
  steps_per_sample: 50
  warmup_steps: 1000
```
